package Vista;

public class frameMenu extends javax.swing.JFrame {

    public frameMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbIniciarJuego = new javax.swing.JButton();
        jbInstrucciones = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jlFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbIniciarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonPlay.png"))); // NOI18N
        jbIniciarJuego.setPreferredSize(new java.awt.Dimension(120, 120));
        jbIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(jbIniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 367, 120, 120));

        jbInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonInstrucciones.png"))); // NOI18N
        jbInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(jbInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 370, 120, 120));

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonExit.png"))); // NOI18N
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 367, 120, 120));

        jlFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoMenu.png"))); // NOI18N
        jlFondoMenu.setText("..");
        getContentPane().add(jlFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarJuegoActionPerformed
        new frameSelectPJ().setVisible(true);
    }//GEN-LAST:event_jbIniciarJuegoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInstruccionesActionPerformed
        new frameInstrucciones().setVisible(true);
    }//GEN-LAST:event_jbInstruccionesActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMenu().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbIniciarJuego;
    private javax.swing.JButton jbInstrucciones;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlFondoMenu;
    // End of variables declaration//GEN-END:variables
}
